#!/bin/sh

set -x

rm -rf ~/.ssh/known_hosts
if [[ "$1" == "dev" ]]; then
  docker-compose -f ../docker-compose-dev.yml down
elif [[ "$1" == "prod" ]]; then
  docker-compose down
else
  echo 'input $1'
fi
